# IMPORTANT: packages listed here should be synced to
# run_app.R and DESCRIPTION

library(aws.s3)
library(bslib)  # bs_theme()
library(curl)
library(DT)
library(flexdashboard)  # gaugeOutput()
library(glue)
library(highcharter)
library(lubridate)
library(openssl)
library(REDCapR)
library(rmarkdown)  # pandoc_available()
library(shiny)
library(shinyanimate)
library(shiny.i18n)  # i18n$t()
library(shinyjs)
library(shinyWidgets)  # chooseSliderSkin()
library(tidyverse)