---
title: "ACORN Lab File Overview"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message = FALSE, echo = FALSE}
 if (input$format_lab_data == "WHONET .dBase") {
    path_lab_file <- input$file_lab_dba[[1, "datapath"]]
    dta <- foreign::read.dbf(path_lab_file, as.is = TRUE)
  }
  
  if (input$format_lab_data == "WHONET .SQLite") {
    path_lab_file <- input$file_lab_sql[[1, "datapath"]]
    dta <- DBI::dbConnect(RSQLite::SQLite(), path_lab_file)
    dta <- as.data.frame(DBI::dbReadTable(dta, "Isolates"))
  }
  
  if (input$format_lab_data == "Tabular") {
    path_lab_file <- input$file_lab_tab[[1, "datapath"]]
    extension_file_lab_data <- tools::file_ext(path_lab_file)
    
    if (extension_file_lab_data == "csv")  dta <- readr::read_csv(path_lab_file, guess_max = 10000)
    if (extension_file_lab_data == "txt")  dta <- readr::read_tsv(path_lab_file, guess_max = 10000)
    if (extension_file_lab_data %in% c("xls", "xlsx")) dta <- readxl::read_excel(path_lab_file, guess_max = 10000)
  }
```

For each column of the lab file provided, find in the table below:

- name of the column
- type of the column
- number of missing values for the column
- number of NON missing values for the column
- two randomly selected values for the column 


```{r}
missing_val <- function(x) sum(is.na(x))
non_missing_val <- function(x) sum(! is.na(x))

DT::datatable(
    data.frame(
      column_name = names(dta),
      type     = apply(dta, 2, typeof),
      missing_val = apply(dta, 2, missing_val),
      non_missing_val = apply(dta, 2, non_missing_val),
      random_val_1 = apply(dta, 2, sample, size = 1),
      random_val_2 = apply(dta, 2, sample, size = 1)
    ),
    rownames = FALSE,
    filter = "top",
    style = "bootstrap",
    options = list(scrollX = TRUE, scrollY = 600, paging = FALSE, dom = "lrtip")
  )
```


