source("./www/R/reset_filters/reset_filter_enrolments.R", local = TRUE)

source("./www/R/reset_filters/reset_filter_surveillance_cat_input.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_ward_type.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_date_enrolment.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_age_cat.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_diagnosis_initial.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_diagnosis_final.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_clinical_severity.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_outcome.R", local = TRUE)
source("./www/R/reset_filters/reset_filter_transfer.R", local = TRUE)